replicaCount: 3

image:
  repository: devops-workshop-app
  tag: v2
  pullPolicy: IfNotPresent

appVersion: "1.0.0"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50

probes:
  path: /health
